name: CI (DevContainer Build & Test)

on:
  workflow_call:
    inputs:
      container_tag:
        description: 'Docker image tag'
        required: true
        type: string
      upload_container:
        description: 'Upload Docker image to registry'
        required: false
        type: boolean
        default: false

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Prepare .env-dev from sample
        run: |

          # 1. Rename the sample file
          cp sample.env-dev .env-dev
          
          # 2. Inject api secrets
          sed -i "s|{REPLACE_WITH_YOUR_CUSTOM_JWT_SECRET}|${{ secrets.APIKEY_JWT_SECRET }}|g" .env-dev
          sed -i "s|{REPLACE_WITH_YOUR_CUSTOM_COOKIE_SECRET}|${{ secrets.COOKIE_SECRET }}|g" .env-dev
          
          # 3. Inject sys user
          sed -i "s|{REPLACE_WITH_YOUR_CUSTOM_SYS_FIRSTNAME}|${{ secrets.SYS_USER_FIRST }}|g" .env-dev
          sed -i "s|{REPLACE_WITH_YOUR_CUSTOM_SYS_LASTNAME}|${{ secrets.SYS_USER_FIRST }}|g" .env-dev
          sed -i "s|{REPLACE_WITH_YOUR_CUSTOM_SYS_EMAIL}|${{ secrets.SYS_USER_EMAIL }}|g" .env-dev
          sed -i "s|{REPLACE_WITH_YOUR_CUSTOM_SYS_USERNAME}|${{ secrets.SYS_USER_USERNAME }}|g" .env-dev
          sed -i "s|{REPLACE_WITH_YOUR_CUSTOM_SYS_PASSWORD}|${{ secrets.SYS_USER_PASS }}|g" .env-dev
          
          # 4. Inject test user
          sed -i "s|{REPLACE_WITH_YOUR_CUSTOM_TEST_USER_PASSWORD}|${{ secrets.TEST_USER_PASS }}|g" .env-dev
          sed -i "s|{REPLACE_WITH_YOUR_CUSTOM_TEST_USER_USERNAME}|${{ vars.TEST_USER_USERNAME }}|g" .env-dev

          # debug
          cat .env-dev

      - name: Prepare .env-prod from sample
        run: |

          # 1. Rename the sample file
          cp sample.env-prod .env-prod
          
          # 2. Inject api secrets
          sed -i "s|{REPLACE_WITH_YOUR_CUSTOM_JWT_SECRET}|${{ secrets.APIKEY_JWT_SECRET }}|g" .env-prod
          sed -i "s|{REPLACE_WITH_YOUR_CUSTOM_COOKIE_SECRET}|${{ secrets.COOKIE_SECRET }}|g" .env-prod
          
          # 3. Inject sys user
          sed -i "s|{REPLACE_WITH_YOUR_CUSTOM_SYS_FIRSTNAME}|${{ secrets.SYS_USER_FIRST }}|g" .env-prod
          sed -i "s|{REPLACE_WITH_YOUR_CUSTOM_SYS_LASTNAME}|${{ secrets.SYS_USER_FIRST }}|g" .env-prod
          sed -i "s|{REPLACE_WITH_YOUR_CUSTOM_SYS_EMAIL}|${{ secrets.SYS_USER_EMAIL }}|g" .env-prod
          sed -i "s|{REPLACE_WITH_YOUR_CUSTOM_SYS_USERNAME}|${{ secrets.SYS_USER_USERNAME }}|g" .env-prod
          sed -i "s|{REPLACE_WITH_YOUR_CUSTOM_SYS_PASSWORD}|${{ secrets.SYS_USER_PASS }}|g" .env-prod

      - name: Build and Run DevContainer Task
        uses: devcontainers/ci@v0.3
        with:
          configFile: .devcontainer/devcontainer.json
          runCmd: |

            echo "::notice::Running functional API Tests (BATS)"
            bun run test:api
            
            echo "::notice::Running functional GUI Tests (Playwright)"
            bun run test:gui
            
            echo "::notice::Running load API Tests (Artillery)"
            bun run test:load:smoke:api

            echo "::notice::Running load GUI Tests (Artillery Smoke)"
            bun run test:load:smoke:gui || true

      - name: Upload Playwright Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 14

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: .test/
          retention-days: 7

      - name: Log in to Docker Hub
        if: ${{ inputs.upload_container }}
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build and Push Docker Image
        if: ${{ inputs.upload_container }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ vars.DOCKER_REPOSITORY }}:${{ inputs.container_tag }}
            ${{ vars.DOCKER_REPOSITORY }}:latest
