name: Pull Request CI

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'docs/**'

jobs:
  call-build:
    uses: ./.github/workflows/build.yml
    with:
      container_tag: "pr-${{ github.event.pull_request.number }}"
      upload_container: false
    secrets: inherit
